bootdo:
  username: wangdd6
  password: wangdd6
  upyuname: blog-image123
  uploadPath: https://haozy.yohaoyun.com
  up_username: wanghby123
  up_password: u371SKHPNAV4g8I577xHzMF3nIHqNb52
  baiduToken: pm8X7Vzf13hK8cGw
  domain: https://haozyx.com
logging:
  level:
    root: error
    com.bootdo: info
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://154.221.16.40:3306/w_mydata?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: wanghby1
    password: Zhangsan1.
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  http:
    multipart:
      enabled: false
      
      